version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: wasel_db
    restart: always
    environment:
      POSTGRES_USER: tasneem_admin
      POSTGRES_PASSWORD: tasneem1234
      POSTGRES_DB: wasel_database
    ports:
      - "5432:5432"
    volumes:
      - wasel_new_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wasel_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: tasneem_admin
      DB_PASSWORD: tasneem1234
      DB_NAME: wasel_database
      JWT_SECRET: your_super_secret_key
    depends_on:
      - db

volumes:
  wasel_new_data: